### ISSUE TITLE
Deprecated time units used

### ISSUE THREAD

**Issue by holsee** [holsee/chroxy#27]
```
12:46:03.637 pid=<0.342.0> module=Chroxy.ChromeServer [info]  [CHROME: 93] "DevTools listening on ws://127.0.0.1:9223/devtools/browser/15596190-f1d1-4888-911b-38ca580d1225"

12:46:23.060 pid=<0.347.0> module=Plug.Logger [info]  GET /api/v1/connection
warning: deprecated time unit: :nanoseconds. A time unit should be :second, :millisecond, :microsecond, :nanosecond, or a positive integer
  (plug) lib/plug/request_id.ex:60: Plug.RequestId.generate_request_id/0
  (plug) lib/plug/request_id.ex:48: Plug.RequestId.get_request_id/2
  (plug) lib/plug/request_id.ex:42: Plug.RequestId.call/2
  (chroxy) lib/chroxy/endpoint.ex:1: Chroxy.Endpoint.plug_builder_call/2


12:46:23.303 pid=<0.348.0> module=Chroxy.ChromeProxy [debug] Obtained new page from ChromeServer [#PID<0.236.0>]

12:46:23.303 pid=<0.341.0> module=Chroxy.ProxyRouter [debug] put object with key: B6E2D84F83211AC9667C2057ED47D952 - value: #PID<0.348.0>
warning: deprecated time unit: :micro_seconds. A time unit should be :second, :millisecond, :microsecond, :nanosecond, or a positive integer
  (plug) lib/plug/logger.ex:36: anonymous fn/2 in Plug.Logger.call/2
  (logger) lib/logger.ex:867: Logger.normalize_message/2
  (logger) lib/logger.ex:690: Logger.__do_log__/3
  (plug) lib/plug/logger.ex:34: anonymous fn/3 in Plug.Logger.call/2
```

**Comment by holsee** [comment]
Resolved in version > 0.6.0 by Plug deps bump
